version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: tool-box-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api-gateway
    networks:
      - tool-box-net

  postgres:
    image: postgres:14-alpine
    container_name: tool-box-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tool-box-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tool-box-frontend
    networks:
      - tool-box-net
    restart: unless-stopped

  api-gateway:
    build: ./services/api-gateway
    container_name: tool-box-api-gateway
    environment:
      NODE_ENV: production
      PORT: 3020
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE}
    ports:
      - "3020:3020"
    depends_on:
      - postgres
    networks:
      - tool-box-net
    restart: unless-stopped

  password-generator:
    build:
      context: ./services/password-generator
      dockerfile: Dockerfile
    container_name: tool-box-password-generator
    environment:
      NODE_ENV: production
      PORT: 3021
    ports:
      - "3021:3021"
    networks:
      - tool-box-net
    restart: unless-stopped

  pdf-tools:
    build:
      context: ./services/pdf-tools
      dockerfile: Dockerfile
    container_name: tool-box-pdf-tools
    environment:
      NODE_ENV: production
      PORT: 3022
    ports:
      - "3022:3022"
    networks:
      - tool-box-net
    restart: unless-stopped

  media-converter:
    build:
      context: ./services/media-converter
      dockerfile: Dockerfile
    container_name: tool-box-media-converter
    environment:
      NODE_ENV: production
      PORT: 3023
    ports:
      - "3023:3023"
    networks:
      - tool-box-net
    restart: unless-stopped

  notes-service:
    build:
      context: ./services/notes-service
      dockerfile: Dockerfile
    container_name: tool-box-notes-service
    environment:
      NODE_ENV: production
      PORT: 3024
    ports:
      - "3024:3024"
    networks:
      - tool-box-net
    restart: unless-stopped

  whiteboard-service:
    build:
      context: ./services/whiteboard-service
      dockerfile: Dockerfile
    container_name: tool-box-whiteboard-service
    environment:
      NODE_ENV: production
      PORT: 3025
    ports:
      - "3025:3025"
    networks:
      - tool-box-net
    restart: unless-stopped

  password-vault:
    build:
      context: ./services/password-vault
      dockerfile: Dockerfile
    container_name: tool-box-password-vault
    environment:
      NODE_ENV: production
      PORT: 3026
    ports:
      - "3026:3026"
    networks:
      - tool-box-net
    restart: unless-stopped

  tasks-service:
    build:
      context: ./services/tasks-service
      dockerfile: Dockerfile
    container_name: tool-box-tasks-service
    environment:
      NODE_ENV: production
      PORT: 3027
    ports:
      - "3027:3027"
    networks:
      - tool-box-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  tool-box-net:
    driver: bridge